server:
  port: 0

spring:
  application:
    name: eclient

eureka:
  client:

    serviceUrl:
      defaultZone: http://eureka-server1:8761/eureka
      # ????????? ???? Eureka Discovery Client ? Eureka Server

# ????????? ?????? ?????? ????? ??? Eureka Discovery Client ? Eureka Server
logging:

  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %C{1}.[%-5level] %msg%n"
